global:
  scrape_interval: 15s

rule_files:
  - /etc/prometheus/alerts.yml

scrape_configs:
  - job_name: router
    metrics_path: /metrics
    static_configs:
      - targets: ["router:8080"]
  - job_name: node
    metrics_path: /metrics
    static_configs:
      - targets: ["node:8081"]
